---

- name: host | update hostname to inventory hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"
  when:
  - ansible_hostname != inventory_hostname

- name: host | update etc hosts
  become: true
  blockinfile:
    path: /etc/hosts
    create: true
    block: |
      127.0.0.1 localhost
      127.0.1.1 {{ inventory_hostname }}

      # The following lines are desirable for IPv6 capable hosts
      ::1     ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters

      {% if keepalived.enabled is defined and keepalived.enabled %}
      # keepalived vip
      {{ keepalived.vip }}  k8s-master-vip
      {% endif %}

      # k8s master
      {% for host in groups['master'] %}
      {{ hostvars[host].ansible_default_ipv4.address }}  {{ host }}
      {% endfor %}

      # k8s worker
      {% for host in groups['worker'] %}
      {{ hostvars[host].ansible_default_ipv4.address }}  {{ host }}
      {% endfor %}
