---
version: '3.7'
services:
  minio:
    image: minio/minio:RELEASE.2020-05-16T01-33-21Z
    pid: host
    network_mode: host
    volumes:
      - /share/Data/ContainerStation/minio:/data
    environment:
      MINIO_ACCESS_KEY: ""
      MINIO_SECRET_KEY: ""
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
