---
version: "3.7"
services:
  nexus:
    image: sonatype/nexus3:3.25.1
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:ActiveProcessorCount=4 -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    volumes:
      - /share/Data/ContainerStation/nexus:/nexus-data
