---

#
# Below vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#group-variables
#

# Use a specific version of k3s
k3s_release_version: "v1.20"

# Install using hard links rather than symbolic links.
# ...if you are using the system-upgrade-controller you will need to use hard links rather than symbolic links as the controller will not be able to follow symbolic links.
k3s_install_hard_links: true

k3s_server:
  # Network CIDR to use for pod IPs
  cluster-cidr: 10.69.0.0/16
  # Network CIDR to use for service IPs
  service-cidr: 10.96.0.0/16
  flannel-backend: 'none'  # This needs to be in quotes
  disable:
    - traefik
  node-ip: "{{ ansible_host }}"

k3s_become_for_all: true

# Enable debugging
k3s_debug: false
