---

- name: cluster | cilium | load etcd ca file
  become: true
  slurp:
    src: "/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt"
  register: b64_etcd_ca
  when:
  - cilium_kube_router.cilium.etcd is defined
  - cilium_kube_router.cilium.etcd

- name: cluster | cilium | load etcd cert file
  become: true
  slurp:
    src: "/var/lib/rancher/k3s/server/tls/etcd/server-client.crt"
  register: b64_etcd_cert
  when:
  - cilium_kube_router.cilium.etcd is defined
  - cilium_kube_router.cilium.etcd

- name: cluster | cilium | load etcd cert key file
  become: true
  slurp:
    src: "/var/lib/rancher/k3s/server/tls/etcd/server-client.key"
  register: b64_etcd_cert_key
  when:
  - cilium_kube_router.cilium.etcd is defined
  - cilium_kube_router.cilium.etcd

- name: cluster | cilium | deploy secret to k3s manifest directory
  become: true
  blockinfile:
    path: "{{ k3s_server_manifests_dir }}/cilium-etcd-secrets.yaml"
    create: true
    block: |
      ---
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: cilium-etcd-secrets
        namespace: kube-system
      data:
        etcd-client-ca.crt: "{{ b64_etcd_ca.content }}"
        etcd-client.crt: "{{ b64_etcd_cert.content }}"
        etcd-client.key: "{{ b64_etcd_cert_key.content }}"
  when:
  - cilium_kube_router.cilium.etcd is defined
  - cilium_kube_router.cilium.etcd

- name: cluster | cilium | deploy configuration to k3s manifest directory
  become: true
  template:
    src: "cilium-helmchart.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/cilium-helmchart.yaml"
    mode: 0644

- name: cluster | cilium | deploy kube-router to k3s manifest directory
  become: true
  template:
    src: "kube-router.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/kube-router.yaml"
    mode: 0644
