---

- name: cluster | calico | get all calicoctl releases
  get_url:
    url: https://api.github.com/repos/projectcalico/calicoctl/releases
    dest: /tmp/calicoctl.releases.json

- name: cluster | calico | get latest calicoctl release version
  shell: >
    cat /tmp/calicoctl.releases.json | jq --raw-output '.[0].tag_name'
  register: calicoctl_latest_release

- name: cluster | calico | download latest calicoctl
  become: yes
  get_url:
    url: "https://github.com/projectcalico/calicoctl/releases/download/{{ calicoctl_latest_release.stdout_lines[0] }}/calicoctl-linux-amd64"
    dest: "/usr/local/bin/calicoctl"
    mode: 0755

- name: cluster | calico | deploy tigera operator to k3s manifest directory
  become: true
  get_url:
    url: "{{ calico.operator_manifest }}"
    dest: "{{ k3s_server_manifests_dir }}/tigera-operator.yaml"
    mode: 0644

- name: cluster | calico | deploy configuration to k3s manifest directory
  become: true
  blockinfile:
    path: "{{ k3s_server_manifests_dir }}/calico-installation.yaml"
    create: true
    block: |
      ---
      apiVersion: operator.tigera.io/v1
      kind: Installation
      metadata:
        name: default
      spec:
        calicoNetwork:
          ipPools:
          - blockSize: 26
            cidr: "{{ k3s_service_cidr }}"
            encapsulation: IPIPCrossSubnet
            natOutgoing: Enabled
            nodeSelector: all()

- name: cluster | calico | deploy BGP-peer to k3s manifest directory
  become: true
  blockinfile:
    path: "{{ k3s_server_manifests_dir }}/calico-bgppeer.yaml"
    create: true
    block: |
      ---
      apiVersion: crd.projectcalico.org/v1
      kind: BGPPeer
      metadata:
        name: global
      spec:
        peerIP: {{ calico.bgp.peer }}
        asNumber: {{ calico.bgp.as }}
  when: 
  - calico.bgp.enabled is defined 
  - calico.bgp.enabled

- name: cluster | calico | deploy BGP-configuration to k3s manifest directory
  become: true
  blockinfile:
    path: "{{ k3s_server_manifests_dir }}/calico-bgpconfiguration.yaml"
    create: true
    block: |
      ---
      apiVersion: crd.projectcalico.org/v1
      kind: BGPConfiguration
      metadata:
        name: default
      spec:
        serviceExternalIPs:
        - cidr: {{ calico.bgp.externalIPs }}
  when: 
  - calico.bgp.enabled is defined 
  - calico.bgp.enabled

#
# Enable eBPF and DSR
# https://docs.projectcalico.org/maintenance/enabling-bpf
#

- name: cluster | calico-ebpf | deploy eBPF configuration to k3s manifest directory
  become: true
  blockinfile:
    path: "{{ k3s_server_manifests_dir }}/calico-ebpf-configmap.yaml"
    create: true
    block: |
      ---
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: kubernetes-services-endpoint
        namespace: tigera-operator
      data:
        KUBERNETES_SERVICE_HOST: "{{ k3s_control_node_address }}"
        KUBERNETES_SERVICE_PORT: "6443"
  when:
  - calico.ebpf.enabled is defined
  - calico.ebpf.enabled

- name: cluster | calico-ebpf | wait for resources to be deployed
  pause:
    seconds: "30"
  when:
  - calico.ebpf.enabled is defined
  - calico.ebpf.enabled

- name: cluster | calico-ebpf | enable eBPF
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
    DATASTORE_TYPE: "kubernetes"
  shell: >
    calicoctl patch felixconfiguration default --patch='{"spec": {"bpfEnabled": true}}'
  when:
  - calico.ebpf.enabled is defined
  - calico.ebpf.enabled

- name: cluster | calico-ebpf | enable DSR
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
    DATASTORE_TYPE: "kubernetes"
  shell: >
    calicoctl patch felixconfiguration default --patch='{"spec": {"bpfExternalServiceMode": "DSR"}}'
  when:
  - calico.ebpf.enabled is defined
  - calico.ebpf.enabled
