---

- include: kubeconfig.yml
  tags:
  - kubeconfig

- include: meta.yml
  tags:
  - meta

- include: prometheus-operator-crds.yml
  tags:
  - prometheus-operator-crds

- include: registry.yml
  when: (registry.cache.enabled is defined 
          and registry.cache.enabled) 
        or (registry.custom.enabled is defined 
          and registry.custom.enabled)
  tags:
  - registry

